---
version: "3"
services:
  7dtd-server-original:
    image: didstopia/7dtd-server
    container_name: 7dtd-server-original
    environment:
      # | SEVEN_DAYS_TO_DIE_START_MODE   | 0 (Default) | server should update and then start |
      # | SEVEN_DAYS_TO_DIE_START_MODE | 1 | server should only update |
      # | SEVEN_DAYS_TO_DIE_START_MODE | 2 | server should only start |
      - SEVEN_DAYS_TO_DIE_START_MODE=0
      # ```SEVEN_DAYS_TO_DIE_UPDATE_CHECKING``` is ```"0"``` 
      # *Fully automatic updates*(default = disabled). Once a server update hits Steam, it'll restart the server and trigger the automatic update. You can enable this by setting ```SEVEN_DAYS_TO_DIE_UPDATE_CHECKING``` to ```"1"```
      - SEVEN_DAYS_TO_DIE_UPDATE_CHECKING=1
      - SEVEN_DAYS_TO_DIE_SERVER_PASSWORD=${SEVEN_DAYS_TO_DIE_SERVER_PASSWORD}
      - SEVEN_DAYS_TO_DIE_TELNET_PASSWORD=${SEVEN_DAYS_TO_DIE_TELNET_PASSWORD}
      - SEVEN_DAYS_TO_DIE_SERVER_STARTUP_ARGUMENTS=-quit -batchmode -nographics -dedicated
      - SEVEN_DAYS_TO_DIE_CONFIG_FILE=/app/.local/share/7DaysToDie/serverconfig.xml
    ports:
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"
      - "26903:26903/udp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8082:8082/tcp"
    volumes:
      - ./7dtd_data/data/:/app/.local/share/7DaysToDie
      - ./7dtd_data/game/:/steamcmd/7dtd
      - ./7dtd_data/mods/:/steamcmd/7dtd/Mods 
    restart: unless-stopped
